### PR TITLE
changed from using grok to csv and updated interfaces

### PR DESCRIPTION
**Pull request by tiny6996**
all interfaces are now able to be listed as LAN or WAN. I changed the log parsing to use tail and a csv pattern instead of a grok pattern, and I updated the ip and dnsbl counts to use a stat panel so they are compatible with grafana 7

### CODE REVIEW

**Comment by VictorRobellini** [comment]
I've had the migration to tail on my list for the couple weeks.   Thank you

**Comment by VictorRobellini** [comment]
I merged before testing.  Something prevents the queries and graphs from loading.  Can you re-export the dashboard and make sure you select "Export for sharing externally"  I'm not sure if that was the issue, but the graphs were blank and the queries never loaded.

**Comment by tiny6996** [comment]
I submitted a new PR after exporting it for sharing externally and I was able to import it. The other issue might be that I am using grafana 7.0

**Comment by VictorRobellini** [comment]
That makes perfect sense.  I need to figure out the best way to merge at this point.  I'll most likely convert the widgets back so they work with older versions of Grafana.  7.0 came out very recently (last week-ish) and I don't want to impact other users that have not upgraded yet.

**Comment by tiny6996** [comment]
I will submit a fresh pull request after install grafana 6.7.3 on a test box and rebuild the dashboard

**Comment by VictorRobellini** [comment]
Quick note, the CSV stuff is broken.  I migrated to tail and grok and fixed the parsing errors.  The issue with CSV is that it doesn't use the timestamp from the log unless you configure it to do so and I hit [this issue](https://github.com/influxdata/telegraf/issues/8948) when trying to implement it.  I went with tail and grok and fixed a bunch of parsing issues while I was at it.

**Pull request merged**
